- name: Set istio release tag
  set_fact:
    release_tag: "{{ istio_release_tag }}"

- name: Get the tagged release
  uri:
    url: "{{ github_url }}/{{ istio_repo }}/releases/{{ release_tag }}"
    headers: "{{ github_api_http_headers }}"
  register: release

- name: Set version
  set_fact:
    istio_version_to_use: "{{ release.json.tag_name }}"
