steps:
- name: 'gcr.io/istio-io/istio-builder:0.1'
  args: ['make', 'docker', "ISTIO_TAGS=git_latest"]
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'istio/docker:mixer', 'gcr.io/$PROJECT_ID/mixer:$BUILD_ID']
images:
- 'gcr.io/$PROJECT_ID/mixer'
- 'gcr.io/$PROJECT_ID/pilot'
- 'gcr.io/$PROJECT_ID/proxy_debug'
- 'gcr.io/$PROJECT_ID/proxy_init'
- 'gcr.io/$PROJECT_ID/istio-ca'
timeout: 1800s

